feat: create and upload fallback remote server

diff --git a/build/azure-pipelines/linux/product-build-linux.yml b/build/azure-pipelines/linux/product-build-linux.yml
--- a/build/azure-pipelines/linux/product-build-linux.yml
+++ b/build/azure-pipelines/linux/product-build-linux.yml
@@ -103,6 +103,8 @@ steps:
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
     - script: |
         set -e
+        # To workaround the issue of yarn not respecting the registry value from .npmrc
+        yarn config set registry "$NPM_REGISTRY"
 
         for i in {1..5}; do # try 5 times
           yarn --cwd build --frozen-lockfile --check-files && break
@@ -113,7 +115,16 @@ steps:
           echo "Yarn failed $i, trying again..."
         done
 
-        ./build/azure-pipelines/linux/install.sh
+        source ./build/azure-pipelines/linux/setup-env.sh
+
+        for i in {1..5}; do # try 5 times
+          yarn --frozen-lockfile --check-files && break
+          if [ $i -eq 3 ]; then
+            echo "Yarn failed too many times" >&2
+            exit 1
+          fi
+          echo "Yarn failed $i, trying again..."
+        done
       env:
         npm_config_arch: $(NPM_ARCH)
         VSCODE_ARCH: $(VSCODE_ARCH)
@@ -127,45 +138,9 @@ steps:
     - script: |
         set -e
 
-        TRIPLE="x86_64-linux-gnu"
-        if [ "$VSCODE_ARCH" == "arm64" ]; then
-          TRIPLE="aarch64-linux-gnu"
-        elif [ "$VSCODE_ARCH" == "armhf" ]; then
-          TRIPLE="arm-rpi-linux-gnueabihf"
-        fi
-
-        # Get all files with .node extension from remote/node_modules folder
-        files=$(find remote/node_modules -name "*.node")
-
-        # Check if any file has dependency of GLIBC > 2.28 or GLIBCXX > 3.4.25
-        for file in $files; do
-          glibc_version="2.28"
-          glibcxx_version="3.4.25"
-          while IFS= read -r line; do
-            if [[ $line == *"GLIBC_"* ]]; then
-              version=$(echo "$line" | awk '{print $5}' | tr -d '()')
-              version=${version#*_}
-              if [[ $(printf "%s\n%s" "$version" "$glibc_version" | sort -V | tail -n1) == "$version" ]]; then
-                glibc_version=$version
-              fi
-            elif [[ $line == *"GLIBCXX_"* ]]; then
-              version=$(echo "$line" | awk '{print $5}' | tr -d '()')
-              version=${version#*_}
-              if [[ $(printf "%s\n%s" "$version" "$glibcxx_version" | sort -V | tail -n1) == "$version" ]]; then
-                glibcxx_version=$version
-              fi
-            fi
-          done < <("$PWD/.build/sysroots/$TRIPLE/$TRIPLE/bin/objdump" -T "$file")
-
-          if [[ "$glibc_version" != "2.28" ]]; then
-            echo "Error: File $file has dependency on GLIBC > 2.28"
-            exit 1
-          fi
-          if [[ "$glibcxx_version" != "3.4.25" ]]; then
-            echo "Error: File $file has dependency on GLIBCXX > 3.4.25"
-            exit 1
-          fi
-        done
+        EXPECTED_GLIBC_VERSION="2.28" \
+        EXPECTED_GLIBCXX_VERSION="3.4.25" \
+        ./build/azure-pipelines/linux/verify-glibc-requirements.sh
       condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
       displayName: Check GLIBC and GLIBCXX dependencies in remote/node_modules
 
@@ -318,6 +293,71 @@ steps:
         echo "##vso[task.setvariable variable=SNAP_PATH]$ARCHIVE_PATH"
       displayName: Prepare snap package
 
+    - script: |
+        set -e
+        # Delete remote/node_modules to build with fallback toolchain
+        rm -rf remote/node_modules
+        rm -rf ../vscode-reh-linux-$(VSCODE_ARCH)
+        rm -rf ../vscode-server-linux-$(VSCODE_ARCH)
+
+        # To workaround the issue of yarn not respecting the registry value from .npmrc
+        yarn config set registry "$NPM_REGISTRY"
+
+        export VSCODE_SYSROOT_PREFIX='-glibc-2.17'
+        source ./build/azure-pipelines/linux/setup-env.sh --only-remote
+
+        # reinstall oss remote node_modules with fallback toolchain
+        for i in {1..5}; do # try 5 times
+          yarn --cwd remote --frozen-lockfile --check-files && break
+          if [ $i -eq 3 ]; then
+            echo "Yarn failed too many times" >&2
+            exit 1
+          fi
+          echo "Yarn failed $i, trying again..."
+        done
+
+        # reinstall distro remote node_modules with fallback toolchain
+        for i in {1..5}; do # try 5 times
+          yarn --cwd .build/distro/npm/remote --frozen-lockfile --check-files && break
+          if [ $i -eq 3 ]; then
+            echo "Yarn failed too many times" >&2
+            exit 1
+          fi
+          echo "Yarn failed $i, trying again..."
+        done
+
+        # mixing in distro node_modules
+        node build/azure-pipelines/distro/mixin-npm -- .build/distro/npm/remote
+
+        EXPECTED_GLIBC_VERSION="2.17" \
+        EXPECTED_GLIBCXX_VERSION="3.4.24" \
+        ./build/azure-pipelines/linux/verify-glibc-requirements.sh
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          exit $exit_code
+        fi
+
+        yarn gulp vscode-reh-linux-$(VSCODE_ARCH)-min-ci
+        mv ../vscode-reh-linux-$(VSCODE_ARCH) ../vscode-server-linux-$(VSCODE_ARCH) # TODO@joaomoreno
+        ARCHIVE_PATH=".build/linux/server/vscode-server-linux-$(VSCODE_ARCH).tar.gz"
+        mkdir -p $(dirname $ARCHIVE_PATH)
+        tar --owner=0 --group=0 -czf $ARCHIVE_PATH -C .. vscode-server-linux-$(VSCODE_ARCH)
+        echo "##vso[task.setvariable variable=SERVER_FALLBACK_PATH]$ARCHIVE_PATH"
+      env:
+        npm_config_arch: $(NPM_ARCH)
+        VSCODE_ARCH: $(VSCODE_ARCH)
+        NPM_REGISTRY: "$(NPM_REGISTRY)"
+        GITHUB_TOKEN: "$(github-distro-mixin-password)"
+      displayName: Build server fallback (GCC 7.5.0 glibc 2.17)
+
+    - ${{ if eq(parameters.VSCODE_RUN_INTEGRATION_TESTS, true) }}:
+      - template: product-build-linux-test.yml
+        parameters:
+          VSCODE_QUALITY: ${{ parameters.VSCODE_QUALITY }}
+          VSCODE_RUN_UNIT_TESTS: false
+          VSCODE_RUN_INTEGRATION_TESTS: ${{ parameters.VSCODE_RUN_INTEGRATION_TESTS }}
+          VSCODE_RUN_SMOKE_TESTS: false
+
     - task: UseDotNet@2
       inputs:
         version: 6.x
@@ -366,6 +406,11 @@ steps:
       artifact: $(ARTIFACT_PREFIX)vscode_server_linux_$(VSCODE_ARCH)_archive-unsigned
       condition: and(succeededOrFailed(), ne(variables['SERVER_PATH'], ''))
       displayName: Publish server archive
+
+    - publish: $(SERVER_FALLBACK_PATH)
+      artifact: $(ARTIFACT_PREFIX)vscode_server_linux_$(VSCODE_ARCH)_fallback_archive-unsigned
+      condition: and(succeededOrFailed(), ne(variables['SERVER_FALLBACK_PATH'], ''))
+      displayName: Publish server fallback archive
 
     - publish: $(WEB_PATH)
       artifact: $(ARTIFACT_PREFIX)vscode_web_linux_$(VSCODE_ARCH)_archive-unsigned
